### ISSUE TITLE
Active energy

### ISSUE THREAD

**Issue by AdamM83pl** [apichlinski/orno-reader-domoticz#3]
Wartość energii w liczniku zapisywana jest w dwóch rejestrach 7 i 8.
W rejestrze 8 zapisywane są wartości od 0 do 65535, po przekroczeniu tej wartości rejestr 8 zeruje się, a rejestr 7 zwiększa się o 1.
Do wyświetlenia prawidłowej wartości potrzebny jest taki zapis:

active_energy = ((data.registers[7]*65535) + data.registers[8])/1000

**Comment by apichlinski** [comment]
Wrzuciłem nową wersję na mastera.
